/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Plan
         * @description Stub planner: everyone together at each slot's first candidate. The engines replace it.
         */
        post: operations["plan_v1_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Candidate */
        Candidate: {
            /**
             * Place Id
             * Format: uuid
             */
            place_id: string;
            /**
             * Price Cents
             * @description Per person.
             */
            price_cents: number;
            /**
             * Tags
             * @default []
             */
            tags?: string[];
            /**
             * Dietary Tags
             * @default []
             */
            dietary_tags?: ("vegetarian" | "vegan" | "gluten_free" | "halal" | "kosher" | "nut_free" | "dairy_free")[];
            /** Rating */
            rating?: number | null;
            /** Open From */
            open_from?: string | null;
            /** Open Until */
            open_until?: string | null;
            /** Duration Min */
            duration_min: number;
        };
        /** GroupAssignment */
        GroupAssignment: {
            /**
             * Place Id
             * Format: uuid
             */
            place_id: string;
            /** Member Ids */
            member_ids: string[];
        };
        /** GroupOptions */
        GroupOptions: {
            /** Member Ids */
            member_ids: string[];
            /** Options */
            options: components["schemas"]["OptionScore"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** Member */
        Member: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Budget Cents
             * @description Remaining budget for these slots.
             */
            budget_cents?: number | null;
            /**
             * Dietary
             * @default []
             */
            dietary?: ("vegetarian" | "vegan" | "gluten_free" | "halal" | "kosher" | "nut_free" | "dairy_free")[];
            /**
             * Interests
             * @default []
             */
            interests?: string[];
        };
        /** MemberScore */
        MemberScore: {
            /**
             * Member Id
             * Format: uuid
             */
            member_id: string;
            /** Score */
            score: number;
            /** Preference */
            preference: number;
            /** Cost */
            cost: number;
            /** Travel */
            travel: number;
        };
        /** OptionScore */
        OptionScore: {
            /**
             * Place Id
             * Format: uuid
             */
            place_id: string;
            /** Rank */
            rank: number;
            /** Score */
            score: number;
            /** Preference */
            preference: number;
            /** Cost */
            cost: number;
            /** Travel */
            travel: number;
            /** Fairness */
            fairness: number;
        };
        /** Params */
        Params: {
            /**
             * Max Plans
             * @default 3
             */
            max_plans?: number;
            /**
             * Min Group Size
             * @default 2
             */
            min_group_size?: number;
            /**
             * Max Groups Per Slot
             * @default 2
             */
            max_groups_per_slot?: number;
            /**
             * @default {
             *       "preference": 1,
             *       "cost": 0.6,
             *       "travel": 0.4,
             *       "fairness": 0.8,
             *       "split_penalty": 0.3
             *     }
             */
            weights?: components["schemas"]["Weights"];
            /**
             * Time Limit Ms
             * @default 2000
             */
            time_limit_ms?: number;
            /**
             * Engine
             * @description `enumeration` forces the fallback engine (tests).
             * @default auto
             * @enum {string}
             */
            engine?: "auto" | "enumeration";
        };
        /** Pinned */
        Pinned: {
            /**
             * Place Id
             * Format: uuid
             */
            place_id: string;
            /** Member Ids */
            member_ids: string[];
        };
        /** Plan */
        Plan: {
            /** Rank */
            rank: number;
            /** Total Score */
            total_score: number;
            /**
             * Fairness
             * @description The lowest member score.
             */
            fairness: number;
            /** Split */
            split: boolean;
            /** Member Scores */
            member_scores: components["schemas"]["MemberScore"][];
            /** Assignments */
            assignments: components["schemas"]["SlotAssignment"][];
        };
        /** PlanRequest */
        PlanRequest: {
            /**
             * Request Id
             * @description The tool-call ID; echoed and logged.
             */
            request_id: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "initial" | "replan";
            /** Members */
            members: components["schemas"]["Member"][];
            /**
             * Slots
             * @description In time order.
             */
            slots: components["schemas"]["Slot"][];
            /** Travel */
            travel: components["schemas"]["TravelEdge"][];
            /**
             * @default {
             *       "max_plans": 3,
             *       "min_group_size": 2,
             *       "max_groups_per_slot": 2,
             *       "weights": {
             *         "cost": 0.6,
             *         "fairness": 0.8,
             *         "preference": 1,
             *         "split_penalty": 0.3,
             *         "travel": 0.4
             *       },
             *       "time_limit_ms": 2000,
             *       "engine": "auto"
             *     }
             */
            params?: components["schemas"]["Params"];
        };
        /** PlanResponse */
        PlanResponse: {
            /** Request Id */
            request_id: string;
            /**
             * Engine
             * @enum {string}
             */
            engine: "cp_sat" | "enumeration";
            /**
             * Status
             * @enum {string}
             */
            status: "optimal" | "feasible" | "infeasible";
            /** Solve Ms */
            solve_ms: number;
            /** Plans */
            plans: components["schemas"]["Plan"][];
            /**
             * Slot Options
             * @description Voting options per group, for the rank-1 plan.
             */
            slot_options: components["schemas"]["SlotOptions"][];
            /** Infeasible Reasons */
            infeasible_reasons: string[];
        };
        /** Slot */
        Slot: {
            /** Key */
            key: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Together */
            together: boolean;
            /** @description Set for booked or pinned context slots. */
            pinned: components["schemas"]["Pinned"] | null;
            /** Candidates */
            candidates: components["schemas"]["Candidate"][];
        };
        /** SlotAssignment */
        SlotAssignment: {
            /** Slot Key */
            slot_key: string;
            /** Groups */
            groups: components["schemas"]["GroupAssignment"][];
        };
        /** SlotOptions */
        SlotOptions: {
            /** Slot Key */
            slot_key: string;
            /** Groups */
            groups: components["schemas"]["GroupOptions"][];
        };
        /** TravelEdge */
        TravelEdge: {
            /**
             * From Place Id
             * Format: uuid
             */
            from_place_id: string;
            /**
             * To Place Id
             * Format: uuid
             */
            to_place_id: string;
            /** Minutes */
            minutes: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Weights */
        Weights: {
            /**
             * Preference
             * @default 1
             */
            preference?: number;
            /**
             * Cost
             * @default 0.6
             */
            cost?: number;
            /**
             * Travel
             * @default 0.4
             */
            travel?: number;
            /**
             * Fairness
             * @default 0.8
             */
            fairness?: number;
            /**
             * Split Penalty
             * @default 0.3
             */
            split_penalty?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    plan_v1_plan_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
